terraform {
  required_version = ">= 1.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Per-service AWS region — set at scaffold time from the form.
# Different services can target different regions based on data locality,
# latency requirements, or compliance constraints.
provider "aws" {
  region = "us-west-2"
}

# CodePipeline for cp-test-1778484017 → usa
# Region: us-west-2
#
# This file was generated by the Backstage scaffolder template. It instantiates
# the shared `codepipeline` Terraform module. Update inputs here, not in the module.
#
# To apply: this is normally picked up by the IaC repo's Terraform CI on merge.

module "cp_test_1778484017_usa" {
  source = "../../../modules/codepipeline"

  pipeline_name      = "cp-test-1778484017-usa"
  service_name       = "cp-test-1778484017"
  market             = "usa"
  region             = "us-west-2"
  group              = "commerce/orderas"

  source_repo        = "priyankaajbhagatt-collab/cp-test-1778484017"
  source_branch      = "main"

  build_image        = "java"
  buildspec_path     = "buildspec.yml"

  # CD stage notifies ArgoCD via webhook — app naming convention matches
  # what CompositeLiveProvider.linkArgoApps() expects.
  argocd_app_name    = "cp-test-1778484017-usa"

  tags = {
    Service     = "cp-test-1778484017"
    Market      = "usa"
    Region      = "us-west-2"
    Group       = "commerce/orderas"
    ManagedBy   = "backstage-scaffolder"
  }
}

output "pipeline_arn" {
  value = module.cp_test_1778484017_usa.pipeline_arn
}
