terraform {
  required_version = ">= 1.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Per-service AWS region — set at scaffold time from the form.
# Different services can target different regions based on data locality,
# latency requirements, or compliance constraints.
provider "aws" {
  region = "us-east-1"
}

# CodePipeline for test-insights-api-finalv1 → vnm
# Region: us-east-1
#
# This file was generated by the Backstage scaffolder template. It instantiates
# the shared `codepipeline` Terraform module. Update inputs here, not in the module.
#
# To apply: this is normally picked up by the IaC repo's Terraform CI on merge.

module "test_insights_api_finalv1_vnm" {
  source = "../../../modules/codepipeline"

  pipeline_name      = "test-insights-api-finalv1-vnm"
  service_name       = "test-insights-api-finalv1"
  market             = "vnm"
  region             = "us-east-1"
  group              = "commerce/orderas"

  source_repo        = "priyankaajbhagatt-collab/test-insights-api-finalv1"
  source_branch      = "main"

  build_image        = "python"
  buildspec_path     = "buildspec.yml"

  # CD stage notifies ArgoCD via webhook — app naming convention matches
  # what CompositeLiveProvider.linkArgoApps() expects.
  argocd_app_name    = "test-insights-api-finalv1-vnm"

  tags = {
    Service     = "test-insights-api-finalv1"
    Market      = "vnm"
    Region      = "us-east-1"
    Group       = "commerce/orderas"
    ManagedBy   = "backstage-scaffolder"
  }
}

output "pipeline_arn" {
  value = module.test_insights_api_finalv1_vnm.pipeline_arn
}
