terraform {
  required_version = ">= 1.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# CodePipeline for e2e-demo-1778418720 → usa
#
# This file was generated by the Backstage java-service / python-service
# scaffolder template. It instantiates the shared `codepipeline` Terraform
# module. Update inputs here, not in the module.
#
# To apply: this is normally picked up by the IaC repo's Terraform CI on merge.

module "e2e_demo_1778418720_usa" {
  source = "../../../modules/codepipeline"

  pipeline_name      = "e2e-demo-1778418720-usa"
  service_name       = "e2e-demo-1778418720"
  market             = "usa"
  group              = "commerce/orderas"

  source_repo        = "priyankaajbhagatt-collab/e2e-demo-1778418720"
  source_branch      = "main"

  build_image        = "java"
  buildspec_path     = "buildspec.yml"

  # CD stage notifies ArgoCD via webhook — app naming convention matches
  # what CompositeLiveProvider.linkArgoApps() expects.
  argocd_app_name    = "e2e-demo-1778418720-usa"

  tags = {
    Service     = "e2e-demo-1778418720"
    Market      = "usa"
    Group       = "commerce/orderas"
    ManagedBy   = "backstage-scaffolder"
  }
}

output "pipeline_arn" {
  value = module.e2e_demo_1778418720_usa.pipeline_arn
}
