terraform {
  required_version = ">= 1.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# CodePipeline for insights-api → can
#
# This file was generated by the Backstage java-service / python-service
# scaffolder template. It instantiates the shared `codepipeline` Terraform
# module. Update inputs here, not in the module.
#
# To apply: this is normally picked up by the IaC repo's Terraform CI on merge.

module "insights_api_can" {
  source = "../../../modules/codepipeline"

  pipeline_name      = "insights-api-can"
  service_name       = "insights-api"
  market             = "can"
  group              = "commerce/orderas"

  source_repo        = "priyankaajbhagatt-collab/insights-api"
  source_branch      = "main"

  build_image        = "python"
  buildspec_path     = "buildspec.yml"

  # CD stage notifies ArgoCD via webhook — app naming convention matches
  # what CompositeLiveProvider.linkArgoApps() expects.
  argocd_app_name    = "insights-api-can"

  tags = {
    Service     = "insights-api"
    Market      = "can"
    Group       = "commerce/orderas"
    ManagedBy   = "backstage-scaffolder"
  }
}

output "pipeline_arn" {
  value = module.insights_api_can.pipeline_arn
}
